# infra/services/vertex-e-svc/stg-job-migration.yaml
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: vertex-e-svc-migrate-stg
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "doppel-stg:asia-northeast1:doppel-stg-mysql-primary"
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: '[{"network":"projects/mitra-shared-network/global/networks/mitra-vpc-main-shared","subnetwork":"projects/mitra-shared-network/regions/asia-northeast1/subnetworks/mitra-subnet-stg-tokyo-doppel-domain"}]'
    spec:
      taskCount: 1
      template:
        spec:
          serviceAccountName: cd-exec@doppel-stg.iam.gserviceaccount.com
          timeoutSeconds: 300
          maxRetries: 1
          containers:
            - name: vertex-e-svc
              image: vertex-e-svc
              command: ["uv"]
              args: ["run", "alembic", "upgrade", "head"]
              resources:
                limits:
                  memory: "2Gi"
              env:
                - name: ENV
                  value: "stg"
                - name: TENANT_ID
                  value: "vertex-e-n5vj7"
                - name: TENANT_NAME
                  value: "vertex-e"
                - name: ALLOW_ORIGINS
                  value: '["https://vertex-e-app-638194985906.asia-northeast1.run.app"]'