# infra/services/c-file-cloudrun-job/dev-cloudrun.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: c-file-cloudrun-job
  annotations:
    run.googleapis.com/ingress: internal
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/target: "75"
        run.googleapis.com/startup-cpu-boost: "true"
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: '[{"network":"projects/mitra-shared-network/global/networks/mitra-vpc-main-shared","subnetwork":"projects/mitra-shared-network/regions/asia-northeast1/subnetworks/mitra-subnet-dev-tokyo-doppel-domain"}]'
    spec:
      serviceAccountName: cd-exec@doppel-dev-461016.iam.gserviceaccount.com
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: c-file-cloudrun-job
          ports:
            - containerPort: 8080
              name: http1
          resources:
            limits:
              cpu: "1000m"
              memory: "2Gi"
          env:
            - name: ENV
              value: "dev"
  traffic:
    - percent: 100