# infra/services/c-file-cloudrun-job/stg-job-migration.yaml
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: c-file-cloudrun-job-migrate-stg
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: '[{"network":"projects/mitra-shared-network/global/networks/mitra-vpc-main-shared","subnetwork":"projects/mitra-shared-network/regions/asia-northeast1/subnetworks/mitra-subnet-stg-tokyo-doppel-domain"}]'
    spec:
      taskCount: 1
      template:
        spec:
          serviceAccountName: cd-exec@doppel-stg.iam.gserviceaccount.com
          timeoutSeconds: 300
          maxRetries: 1
          containers:
            - name: c-file-cloudrun-job
              image: c-file-cloudrun-job
              command: ["uv"]
              args: ["run", "alembic", "upgrade", "head"]
              env:
                - name: ENV
                  value: "stg"