blank_issues_enabled: false  # "白紙のチケット"作成リンクを非表示にする
contact_links:
  - name: 💬 質問・ディスカッション
    url: https://github.com/MitraDataScience/MITRA_X/discussions/categories/q-a
    about: バグではなく、仕様の確認や質問はこちらへ