# infra/services/c-file-svc/prod-job-migration.yaml
apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: c-file-svc-migrate-prod
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: "doppel-prod:asia-northeast1:doppel-prod-mysql-primary"
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: '[{"network":"projects/mitra-shared-network/global/networks/mitra-vpc-main-shared","subnetwork":"projects/mitra-shared-network/regions/asia-northeast1/subnetworks/mitra-subnet-prod-tokyo-doppel-domain"}]'
    spec:
      taskCount: 1
      template:
        spec:
          serviceAccountName: cd-exec@doppel-prod.iam.gserviceaccount.com
          timeoutSeconds: 300
          maxRetries: 1
          containers:
            - name: c-file-svc
              image: c-file-svc
              command: ["uv"]
              args: ["run", "alembic", "upgrade", "head"]
              env:
                - name: ENV
                  value: "prod"